# Jetson single-site deployment config

aibox_id=MF001
cam_id=CAM001

rtsp_url=rtsp://127.0.0.1:8554/mf001
engine_path=/home/nvidia/mudflow_project/model_onnx/EdgeDisNet_fp16_jetson.engine

mqtt_host=192.168.31.185
mqtt_port=1883

confidence_threshold=0.80
stable_window=3
cooldown_sec=10
status_interval_sec=10
class_names=flood,mudslide
snapshot_dir=../runtime/snapshots
log_dir=../runtime/logs
rtsp_reconnect_sec=3
mqtt_reconnect_sec=3
evidence_upload_enabled=true
evidence_upload_url=http://192.168.31.185/api/evidence/upload
evidence_upload_api_key=qMwicMvIHow7QoJo1g/oUnarMSBcIrZ+ioG9fDaa69s=
evidence_upload_timeout_sec=15
